### ISSUE TITLE
Todo: Add Fade-in 

### ISSUE THREAD

**Issue by rfboykin** [ClaytonTurner/power-hour-generator#1]
Add fade-in effect (audio at least, visual a plus) in between videos

**Comment by ClaytonTurner** [comment]
Figured out how to add video/audio fades with ffmpeg. We need to figure out if it's best just to fade out to our beep or add a fade with the beep as well.

The beep is so short that I feel like adding a fade is pointless, but it does seem abrupt and inconsistent to go: song fade -> beep without fade -> song

The transition to beep without fade to song is real abrupt. We could potentially fade in on the second song. This would aid in smoothness and allow easy removal of the beep later if people want it.

**Comment by ClaytonTurner** [comment]
Alright, I'm closing this issue for now. When we have the GUI we can re-open or make a more refined issue.

I have the current setup as: song fades in, song plays, song fades out -> beep -> song fades in, song play, song fades out...
