### ISSUE TITLE
ToDo: Concatenating Videos

### ISSUE THREAD

**Issue by ClaytonTurner** [ClaytonTurner/power-hour-generator#2]
Need to concatenate the videos together still

Don't need python - can just script it up in any language then write a BASH wrapper

**Comment by ClaytonTurner** [comment]
[Nifty Java Solution](https://code.google.com/archive/p/mp4parser/wikis/AppendTracks.wiki)

**Comment by rfboykin** [comment]
Also worth looking into converting videos to alternate format. 

Potentially [.webm](https://www.webmproject.org/)

**Comment by ClaytonTurner** [comment]
I got this working with ffmpeg..

https://github.com/ClaytonTurner/power-hour-generator/commit/7c8723eb1ead313aaaa6e131e82a4ada6aaab241
