### ISSUE TITLE
Unnecessary Files

### ISSUE THREAD

**Issue by ClaytonTurnerOld** [ClaytonTurner/power-hour-generator#9]
Untrack __pycache__/* and the unnecessary .idea/[...] files

There seems to be some weird tracking issues happening with Pycharm and I'm tired of dealing with it for now

**Comment by ClaytonTurner** [comment]
Bleh still happening, gotta sit down and just wildcard the hell out of this stuff one day. Should also add other common config stuff (like vscode)

**Comment by ClaytonTurner** [comment]
https://github.com/ClaytonTurner/power-hour-generator/pull/16
